### PR TITLE
Info and warn logs are directed to Stdout

### PR DESCRIPTION
**Pull request by lukamicoder**

### CODE REVIEW

**Comment by kardianos** [comment]
@lukamicoder I'm not opposed to this, but directing all to stderr was intentional. Specifically I wanted to separate the service logger stream from any normal output for the program.

Do you have a specific use case that causes you to prefer log and info to go to stdout?

**Comment by lukamicoder** [comment]
On systems based on SysVinit, your library creates two files: a log file and an err file. Currently all logs go to the err file which is misleading, hence, my changes.

**Comment by kardianos** [comment]
But this is for the console logger. It should only be used when invoked directly. Can you run a quick test to see if service.Interactive() returns false when running under sysVinit?

Again, the change might be fine, just want to make the right change.

**Comment by lukamicoder** [comment]
It returns true regardless of whether I run it from the terminal or as a service (installed as root).

**Comment by kardianos** [comment]
@lukamicoder Thanks for the report. I will spin up a box that uses sysv to test or modify existing container based tests. I'd prefer to fix the Interactive() call then modify console logger.

**Comment by lukamicoder** [comment]
OK, then I close this pull request.

**Pull request closed without merging**
