### PR TITLE
Multiple fixes/adjustments for Upstart services

### LINKED ISSUE #133: Upstart setuid unknown stanza
It appears that the setuid stanza wasn't added until upstart 1.4. It can probably be solved the same way as the kill stanza was.

As a work around I modified the upstart template to use 
```golang
// The upstart script should stop with an INT or the Go runtime will terminate
// the program before the Stop handler can run.
const upstartScript = `# {{.Description}}

{{if .DisplayName}}description    "{{.DisplayName}}"{{end}}

{{if .HasKillStanza}}kill signal INT{{end}}
{{if .ChRoot}}chroot {{.ChRoot}}{{end}}
{{if .WorkingDirectory}}chdir {{.WorkingDirectory}}{{end}}
start on filesystem or runlevel [2345]
stop on runlevel [!2345]

respawn
respawn limit 10 5
umask 022

console none

pre-start script
    test -x {{.Path}} || { stop; exit 0; }
end script

# Start
exec {{if .UserName}}sudo -E -u {{.UserName}} {{end}}{{.Path}}{{range .Arguments}} {{.|cmd}}{{end}}
`

```

### PR DESCRIPTION
**Pull request by SteelPhase**
This is an initial attempt to resolve the issues I've listed below.

This closes #133, #134, #135, and #138

### CODE REVIEW

**Comment by SteelPhase** [comment]
I am looking into verifying the correctness of this PR, and the validity of the versionAtMost function

**Comment by kardianos** [comment]
Thanks.

This PR looks great. If possible, is there  a way to get the upstart version without invoking init? Some busybox users don't bail when they have an un-recognized flag.

**Comment by SteelPhase** [comment]
I haven't run into that specific issue. but I'll look into that.

**Comment by SteelPhase** [comment]
@kardianos would `/sbin/initctl version` be a better options?

**Pull request merged**
