### PR TITLE
Changed console.go

### PR DESCRIPTION
**Pull request by skunkie**
Changed console.go to send info messages to os.Stdout and display datetime instead of time in log file

### CODE REVIEW

**Comment by kardianos** [comment]
Why? We need to fix interactive for sysv.

**Comment by skunkie** [comment]
Hello Daniel,
Could you please explain.

Regards,
Yuri
26 окт. 2015 г. 17:21 пользователь "Daniel Theophanes" <
notifications@github.com> написал:

**Comment by kardianos** [comment]
What is the rationale for this change? In particular, why are you changing it from Stderr to Stdout? The other changes might be okay.

**Comment by skunkie** [comment]
Info messages are not of the ERROR severity, so in a linux box they should
go to a somefile.log, not somefile.err.
26 окт. 2015 г. 20:41 пользователь "Daniel Theophanes" <
notifications@github.com> написал:

**Comment by clns** [comment]
[GNU Standard Streams](http://www.gnu.org/software/libc/manual/html_node/Standard-Streams.html):

- `stdout` is the normal output from the program
- `stderr` is used for error messages and diagnostics issued by the program

I'm not sure if info messages are considered diagnostics, but since they're logs I think yes, in which case they should go to `stderr`.

**Comment by skunkie** [comment]
Ok, now I see what you meant.
So a program should not use service.Logger for os.Stdout. This rather 
makes a vague sense, as if I only need to log a message, I should use 
the fmt package explicitly.

**Pull request closed without merging**
