### PR TITLE
Fix interaction with systemd

### PR DESCRIPTION
**Pull request by tmaczukin**
The library is using inconsistent names when calling `systemctl`
commands.

Let's say that the service is named `name`. The unit file will be
then named `name.service` - this is the popular pattern used also by
this library.

While for most common commands like `systemctl start` there is no
difference whether `name` or `name.service` will be used as the service
identifier, the `list-unit-files` command expects explicitly the unit
file name.

Currently just the name - without the `.service` suffix - is being used,
which causes the command to return no output, not match the name of the
service and finally respond the status of installed but inactive service
as `StatusUnknown` with `ErrNotInstalled` error. While `StatusStopped`
without any error is expected.

Considering `systemctl` behavior it's just easier to:

- have one method that constructs the `name.service` name,
- use it for all `systemctl` commands calls.

And this is the change that this commit is adding.

### CODE REVIEW

**Comment by mpetavy** [comment]
@kardianos Please review and pull, Thanks

**Comment by djdv** [comment]
For what it's worth, I encountered this problem too and made a similar change. Was going to submit them but didn't get to it.
The commit is here though: https://github.com/djdv/service/commit/3b4ca4320e3c98c8c923bae54a8a04540300ec75

While doing so, I wondered if it would make more sense to use a systemd library like https://github.com/coreos/go-systemd  to interface with the system. Rather than keeping track of unit files, invoking `systemctl` as an external process, and parsing stdout ourselves.
I'm not sure yet if everything is possible that way, but if it is and it seems like a good idea, I'd be willing to try and implement that.
Any opinions on that @kardianos @tmaczukin ?

***
Also, I needed to add support for socket based activation for systemd and launchd services.
Which meant adding comprehension for both the systemd `.service` and `.socket` files separately.
The patches I have seem to work fine, but might be even better with the change mentioned above as well.
(*I'm planning to submit both of those socket-activation patches for systemd+launchd as a PR but I'm in the middle of things and they need another look over)

cc: @mever from https://github.com/kardianos/service/pull/270
You might be interested in this too.

**Comment by kardianos** [comment]
@djdv I did a quick glance at go-systemd and it doesn't appear to provide the functionality that this package requires. Can you link directly to the godoc that would be used?

**Comment by djdv** [comment]
For sure.
I'm not positive, but checking their sub packages there seems to be some overlap.
I think we can replace executing `systemctl` with a dbus connection / interface to systemd via https://pkg.go.dev/github.com/coreos/go-systemd/v22/dbus

I think we could replace the template as well, and use this structure to generate the files
https://pkg.go.dev/github.com/coreos/go-systemd/v22/dbus#UnitFile

It looks like they may also account for the `.socket` unit files already.
I pushed the WIP for my own branch which is adding that feature
https://github.com/djdv/service/commit/0e8696620bdb2e70d22cf809c5e2fbc965d1a263
but I might not need to do that for systemd if this would work instead.

**Pull request merged**
